### ISSUE TITLE
High Level To-Do's

### ISSUE THREAD

**Issue by averywhitted** [averywhitted/Website#1]
# Design

## General

- [ ] Social Icons
	- [ ] Can they show actual icon colors on hover?
- [ ] Buttons
	- [ ] Fill in with color and invert text on hover
- [ ] Accessibility
	- [ ] Make sure contrast is compliant
	- [ ] Make sure images have screen-reader fallback text
## Acting
- [ ] Header Image
	- [ ] Should it be headshots? (Probably)
	- [ ] Can it be a video?
	- [ ] Does each section have it's own header image (acting, artwork, writing, etc...)
- [ ] Figure out how articles work
	- [ ]  Is there a way to dynamically feature them based on date and/or random on page load?
	- [ ] Where are they listed in the source code?
	- [ ] How can I easily add new ones without hardcoding them?
- [ ] Design Resume section
	- [ ] Needs to fit with other sections
	- [ ] Needs to be easy to find
	- [ ] Maybe also access from nav menu?
- [ ] Contact Form
	- [ ] Need to clean up rep info alignment

## 3D Artwork
- [ ] Layout
	- [ ] Is this just a gallery?

## Writing
- [ ] Can you embed articles from Medium?
- [ ] *Future* -- Add articles section for play readings, publications etc...

## Development
- [ ] What is the best way to format this?
- [ ] How are dev portfolios usually designed?
- [ ] Distiguish between web design and game design?
